### ISSUE TITLE
Bootstrap4 dark blue DataTable header transparent

### ISSUE THREAD

**Issue by Bultjer** [primefaces/themes#15]
Using bootstrap4-dark-blue Theme, the surface-hover Variable has a transparent Background. This is fine most of the time, but when the DataTable is used with sortable and scrollable, while hovering over the header, the row below is visible.
![image](https://user-images.githubusercontent.com/22859868/154855924-c2fda3fb-06ce-44fc-a2e2-8a655c954852.png)
``` html
<DataTable value={data} scrollable scrollHeight="100vh">
    <Column field="iconLink" header="Icon"></Column>
    <Column field="shortName" header="Name" sortable></Column>
</DataTable>
```

``` css
.p-datatable .p-sortable-column:not(.p-highlight):not(.p-sortable-disabled):hover {
    background: rgba(255, 255, 255, 0.04);
    color: rgba(255, 255, 255, 0.87);
}
```
